# Generated by Django 3.0.7 on 2020-07-16 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('Main_photo', models.ImageField(upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('mrp_price', models.IntegerField()),
                ('our_price', models.IntegerField()),
                ('Main_photo', models.ImageField(upload_to='photo/')),
                ('size', models.CharField(max_length=100)),
                ('listing_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_topselling', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
    ]
