# Generated by Django 3.0 on 2020-07-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='tel',
        ),
    ]
