# Generated by Django 3.0 on 2020-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200731_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='our_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
