# Generated by Django 3.0 on 2020-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200806_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
