# Generated by Django 3.0 on 2020-08-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200811_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
