# Generated by Django 3.0 on 2020-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
